# Introduction to oop in python


one of the popular approach to solve a programming problem by creating an object .this is known as object oriented programming.


An object has tow charcteristics 

1.   Attributes(Name,Age,Color)
2.   Behaviour(Learn,study,singing,dancing)

In python the concept of oop follows these things:

class:


A class is blueprint for object or logical entity

object:

Blueprint of class or insurance of the class or physical entity

#class classname:

           #same function are variables.
           
           #function -- used to perform specific activity.
           
           #variables -- data(merory).



In [0]:
def test():
    return
test()

In [0]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
      
obj=demo()
obj.test()

test() for the class and method


In [0]:
class demo1:
    def fact(self,n):
      #return the factorial
      fact=1
      while(n!=0):
          fact = fact * n
          n = n -1
      return fact
    
p1 = demo1()
print(p1.fact(5))

120


In [0]:
class demo2:
  
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print('p1 =',self.p1)
        print('p2 =',self.p2)
        
c1=demo2()
c1.accept(10,20)
c1.display()

p1 = 10
p2 = 20


In [0]:
class demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
        
    def add(self,p1,p2):
        return p1 + p2
      
c1 = demo2(10,20)
print(c1.add(100,200))

300


In [0]:
# same inheritance
# parent class
class person(object):
    #constuctor
    def __init__(self,name):
      self.name=name
    def getName(self):
        return self.name
    def isEmployer(self):
        return False

##Python Nummy

Nummy arrays is a bit like python list


Nummy array is a central data structure of the nummy lib

This lib is actually short form of 'Numeric Python'

In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [0]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
lst=[1,0,2,5,3,6,9,5]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(8,)
int64


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
# RE-shape the given array
# numpy.reshape(arrayName,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#Append some Data --Horizontally
#Append some Data --Vertically

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [0]:
#append some Data --Vertically
# vstack(array1,array2) -- will be automatically arranged
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
# Generate random number from NP
a1=np.random.normal(5,0,10)
print(a1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [0]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:
# arange() --particular
# numpy.arrange(start,end,step)
# start -- value
# End -- value
# step -- gap between one value to another value

import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
#Index and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row:",a1[0])

First row: [1 2 3]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column",a1[:,1])

slicing column [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column",a1[:,2])

slicing last column [3 6]


In [0]:
a1=np.random.normal(5,1,10)
print(a1)

[2.35940588 5.96015882 3.89284201 4.67395301 5.61309326 5.65519431
 3.94718747 4.45015718 5.00590739 4.87632778]


In [0]:
# Some match operations on given random numbers
# Min -- returns the least number
# Max -- returns the large number
# Mean -- Mean
# Median -- Median
a1=np.random.normal(5,1,10)
print(a1)
print("Min value",np.min(a1))
print("Max value",np.max(a1))
print("Mean value",np.mean(a1))
print("Median value",np.median(a1))

[2.84943691 6.10465284 3.76171479 6.55049115 3.82088642 4.21883495
 6.39643918 5.71704595 5.82026155 5.02868851]
Min value 2.849436909611411
Max value 6.550491147771025
Mean value 5.026845223204466
Median value 5.372867228868011


In [0]:
# Mutiply of Id arrays
# numpy.dot(x,y) --

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(4,5),(6,7)])
np.dot(c1,c2)

array([[16, 19],
       [36, 43]])